spring.application.name=expense-tracker

# In-memory database. Wiped every restart. Perfect for learning.
spring.datasource.url=jdbc:h2:mem:expensedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let Spring build the tables from our Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# A browser UI to peek inside the database: http://localhost:8080/h2-console
spring.h2.console.enabled=true

server.port=8080